const DB='northstar-db',PASS='160382';let db;const $=s=>document.querySelector(s),esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const read=()=>{try{return JSON.parse(localStorage.getItem(DB))||{students:[],teachers:[],timetables:{}}}catch{return {students:[],teachers:[],timetables:{}}}};const save=()=>localStorage.setItem(DB,JSON.stringify(db));const id=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now());function toast(m){const x=$('#toast');x.textContent=m;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function renderAccounts(){const s=$('#account');s.innerHTML='<option value="admin">Administrator</option>'+db.teachers.filter(t=>t.id!=='admin').map(t=>`<option value="${esc(t.id)}">${esc(t.name)} · Teacher</option>`).join('')}
function renderStudents(){const s=$('#studentList');s.innerHTML=db.students.map(x=>`<div class="management-row"><div><b>${esc(x.name)}</b><small>${esc(x.email)} · ${esc(x.year)} · House: ${esc(x.house)} · Faction: ${esc(x.faction)}</small></div><button data-edit-student="${x.id}">Edit</button><button class="danger-text" data-delete-student="${x.id}">Remove</button></div>`).join('')||'<p>No students yet.</p>';$('#classStudent').innerHTML=db.students.map(x=>`<option value="${x.id}">${esc(x.name)} · ${esc(x.email)}</option>`).join('')}
function renderTeachers(){$('#teacherList').innerHTML=db.teachers.filter(x=>x.id!=='admin').map(x=>`<div class="management-row"><div><b>${esc(x.name)}</b><small>${esc(x.email)}</small></div><button class="danger-text" data-delete-teacher="${x.id}">Remove</button></div>`).join('')||'<p>No additional teachers yet.</p>'}
function renderClasses(){const sid=$('#classStudent').value;const list=db.timetables[sid]||[];$('#classList').innerHTML=list.map(x=>`<div class="management-row"><div><b>${esc(x.subject)}</b><small>${esc(x.day)} ${esc(x.start)}–${esc(x.end)} · ${esc(x.room)} · ${esc(x.teacher)}</small></div><button class="danger-text" data-delete-class="${x.id}">Remove</button></div>`).join('')||'<p>No classes assigned.</p>'}
function render(){renderAccounts();renderStudents();renderTeachers();renderClasses()}
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();if($('#password').value!==PASS){toast('Incorrect password');return}sessionStorage.setItem('northstar-admin',$('#account').value);$('#login').remove();$('#adminApp').hidden=false;render()});$('#signOut').onclick=()=>{sessionStorage.removeItem('northstar-admin');location.reload()};
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.hidden=true);tab.classList.add('active');$('#'+tab.dataset.tab+'Tab').hidden=false;return}const edit=e.target.closest('[data-edit-student]');if(edit){const x=db.students.find(s=>s.id===edit.dataset.editStudent);$('#studentId').value=x.id;$('#studentName').value=x.name;$('#studentEmailAdmin').value=x.email;$('#studentYear').value=x.year;$('#studentHouse').value=x.house||'';$('#studentFaction').value=x.faction||''}const ds=e.target.closest('[data-delete-student]');if(ds&&confirm('Remove this student?')){db.students=db.students.filter(x=>x.id!==ds.dataset.deleteStudent);delete db.timetables[ds.dataset.deleteStudent];save();render();toast('Student removed')}const dt=e.target.closest('[data-delete-teacher]');if(dt&&confirm('Remove this teacher?')){db.teachers=db.teachers.filter(x=>x.id!==dt.dataset.deleteTeacher);save();render();toast('Teacher removed')}const dc=e.target.closest('[data-delete-class]');if(dc){const sid=$('#classStudent').value;db.timetables[sid]=(db.timetables[sid]||[]).filter(x=>x.id!==dc.dataset.deleteClass);save();renderClasses();toast('Class removed')}});
$('#studentForm').addEventListener('submit',e=>{e.preventDefault();const item={id:$('#studentId').value||id(),name:$('#studentName').value.trim(),email:$('#studentEmailAdmin').value.trim().toLowerCase(),year:$('#studentYear').value.trim(),house:$('#studentHouse').value.trim(),faction:$('#studentFaction').value.trim()};const i=db.students.findIndex(x=>x.id===item.id);if(i<0)db.students.push(item);else db.students[i]=item;save();e.target.reset();$('#studentId').value='';render();toast('Student saved')});$('#cancelStudent').onclick=()=>{$('#studentForm').reset();$('#studentId').value=''};$('#teacherForm').addEventListener('submit',e=>{e.preventDefault();db.teachers.push({id:id(),name:$('#teacherName').value.trim(),email:$('#teacherEmail').value.trim().toLowerCase(),role:'Teacher'});save();e.target.reset();render();toast('Teacher added')});$('#classStudent').addEventListener('change',renderClasses);$('#classForm').addEventListener('submit',e=>{e.preventDefault();const sid=$('#classStudent').value;if(!sid)return;const item={id:id(),subject:$('#subject').value.trim(),day:$('#day').value,start:$('#start').value,end:$('#end').value,room:$('#room').value.trim(),teacher:$('#teacher').value.trim(),colour:$('#colour').value};db.timetables[sid]=[...(db.timetables[sid]||[]),item];save();e.target.reset();renderClasses();toast('Class added')});
if(sessionStorage.getItem('northstar-admin')){$('#login').remove();$('#adminApp').hidden=false;db=read();render()}else{db=read();renderAccounts()}
