const DB='northstar-db';
const defaultStudents=[{id:'jordan-smith',name:'Jordan Smith',email:'jordan@school.edu.au',year:'Year 10 · 10A',house:'Aurora',faction:'North',classes:[]}];
const defaultTeachers=[{id:'admin',name:'Administrator',email:'admin@school.edu.au',role:'Administrator'}];
const read=()=>{try{return JSON.parse(localStorage.getItem(DB))||{students:defaultStudents,teachers:defaultTeachers,timetables:{}}}catch{return {students:defaultStudents,teachers:defaultTeachers,timetables:{}}}};
const write=(db)=>localStorage.setItem(DB,JSON.stringify(db));
let db=read(); if(!db.students)db.students=defaultStudents;if(!db.teachers)db.teachers=defaultTeachers;if(!db.timetables)db.timetables={};write(db);
const $=s=>document.querySelector(s), esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const logged=JSON.parse(sessionStorage.getItem('northstar-student')||'null');
function toast(message){const el=$('#toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2400)}
function renderStudent(student){$('#portalApp').hidden=false;$('#studentLogin').remove();$('#sideName').textContent=student.name;$('#sideDetails').textContent=`${student.year} · ${student.house||'No house'}`;const initials=student.name.split(' ').map(x=>x[0]).join('');$('#sideInitials').textContent=initials;$('#topInitials').textContent=initials;$('#greeting').textContent=`Welcome back, ${student.name.split(' ')[0]}`;$('#dateLabel').textContent=new Intl.DateTimeFormat('en-AU',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());const classes=db.timetables[student.id]||student.classes||[];$('#classList').innerHTML=classes.length?classes.slice().sort((a,b)=>`${a.day}${a.start}`.localeCompare(`${b.day}${b.start}`)).map(c=>`<div class="lesson"><div class="lesson-time"><span>${esc(c.start)}</span><small>${esc(c.end)}</small></div><div class="lesson-bar ${esc(c.colour||'purple')}"></div><div class="lesson-details"><strong>${esc(c.subject)}</strong><span>${esc(c.room)} · ${esc(c.teacher)} · ${esc(c.day)}</span></div></div>`).join(''):'<div class="empty-timetable"><div class="empty-calendar-icon">＋</div><strong>No classes have been added yet</strong><span>Your teacher can add classes from the Admin Portal.</span></div>'}
function messages(){let m=$('#messagesModal');if(!m){m=document.createElement('div');m.id='messagesModal';m.className='messages-modal';m.innerHTML='<div class="messages-card"><div class="messages-header"><div><p>COMMUNICATION</p><h2>Direct messages</h2></div><button class="messages-close">×</button></div><div class="message-history"><div class="received">Hi! How can we help?</div></div><form class="message-form"><input required placeholder="Write a message..."><button>Send</button></form></div>';document.body.append(m);m.querySelector('.messages-close').onclick=()=>m.classList.remove('visible');m.onclick=e=>{if(e.target===m)m.classList.remove('visible')};m.querySelector('form').onsubmit=e=>{e.preventDefault();const i=e.target.querySelector('input'),b=document.createElement('div');b.className='sent';b.textContent=i.value;m.querySelector('.message-history').append(b);i.value='';toast('Message sent')}}m.classList.add('visible')}
function section(name){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.section===name));$('#pageTitle').textContent=name;if(name==='Timetable')$('#classList').scrollIntoView({behavior:'smooth'});else if(name==='Direct messages')messages();else toast(`${name} opened`)}
document.addEventListener('click',e=>{const sec=e.target.closest('[data-section]');if(sec){e.preventDefault();section(sec.dataset.section)}const action=e.target.closest('[data-action]')?.dataset.action;if(action==='calendar')toast('Calendar event started');if(action==='search')toast('Search is ready');if(action==='notifications')toast('You have 3 notices');if(action==='notice')toast('Notice opened');if(action==='grades')toast('All results opened');if(e.target.closest('.mobile-menu'))$('#sidebar').classList.toggle('open');if(e.target.closest('.logout-button')){sessionStorage.removeItem('northstar-student');location.reload()}});
$('#studentLoginForm')?.addEventListener('submit',e=>{e.preventDefault();const email=$('#studentEmail').value.trim().toLowerCase();const student=db.students.find(s=>s.email.toLowerCase()===email);if(!student){toast('That email is not registered');return}sessionStorage.setItem('northstar-student',JSON.stringify(student));renderStudent(student)});
if(logged){const student=db.students.find(s=>s.id===logged.id||s.email===logged.email);if(student)renderStudent(student)}
